name: Generate Snapshot Feature
on:
  push:
    branches:
      - 'features/**'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -lha
