name: Generate Snapshot Feature
on:
  push:
    branches:
      - 'features/**'
jobs:
  Build-Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Install JQ to parse JSON
        run: sudo apt-get install -y jq

      - uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags) for Docker
        run: echo 'IMAGE_TAG=$(cat example-app/composer.json | jq .version -r)' >> $GITHUB_ENV

      - name: Building image
        run: "docker build -t rjlabegalini8/bootcamp:${{ env.IMAGE_TAG }}-SNAPSHOT-$GITHUB_RUN_ID ."